export const speakers = [
    "P S K D Ayyappa Swamy",
    "D Srilakshmi",
    "A Parvathi",
    "Lakshmi Sowmya Parchuri",
    "Indra Shekar Reddy B",
    "M Sateesh Kumar",
    "S Rajeswari",
    "Bhanu Kiran",
    "Gattadi Arun",
    "Gellanki Roja",
    "Arvapalli Venkata Raviteja",
    "B Rama Rao",
    "Boya Anil Kumar",
    "Sai Karthik Thotakura",
    "Saggam Nikhil",
    "Ranjith Kumar Manne",
    "Gopi Puppala",
    "Nikhitha",
    "Girish V",
    "PC Rao Challas",
    "Pandurang",
    "Vamsi Raj Chebrolu",
    "Pranay Burande",
    "M Ramya Sri",
    "Soujanya Chinta",
    "SAIKRISHNA PITTA",
    "Eppa Achyuth",
    "Allam Kumar Durga Prasad",
    "Dhanamma",
    "M SADIKH SHARIEFF",
    "Ramya Yarlagadda",
    "Gudivada soumya sri",
    "Bhogadi Venkata Sai Ram",
    "Minna Madhuri",
    "Undi Hima Madhuri",
    "vamshi krishna nune",
    "DURGAPRASAD MUSINI",
    "Gulam Azad Shaik",
    "SAI MANASWI PONNA",
    "MANJUSHA BANDARU",
    "SAMSON KALETI",
    "PRAVEENKUMAR TALARI",
    "SAICHARAN LANKOJI",
    "Rajendra Ambati",
    "HEMA SATYANARAYANA MARELLA",
    "Keerthi priya chodavarpu",
    "Jnana Deepika Mukku",
    "Sirisha Reddy Cheerla",
    "Kethan Sri Venkata Sai Annam",
    "Venkata Ramana Basetti",
    "Venkat Bhanu Sai Zagabathuni",
    "Akhila Patibandla",
    "Padmavati Lalam",
  ];
  
  export const chessPlayers = [
    "Sateesh Kumar Mogalipuvvu",
    "Lankoji Sai Charan",
    "N V S Parvathi Annam",
    "Lakshmi Sowmya Parchuri",
    "Soumya Sri Gudivada",
    "Hima Madhuri Undi",
    "DurgaPrasad Musini",
    "Sri Lakshmi Dasari",
    "Keerthi Priya Chodavarpu",
    "Gorre Manikanta Reddy",
    "Arun Gattadi",
    "Anil Kumar Boya",
    "Pandurang Dawargave",
    "Ambati Rajendra",
    "Jnana Deepika Mukku",
    "Akhila Patibandla",
    "Lalam Padmavati",
    "Sadhik",
    "Nikhil",
    "Bhanu Sai"
  ];
  
  export const carromPlayers = [
    "Girish",
    "Bharathi Gompa",
    "N V S Parvathi Annam",
    "Lakshmi Sowmya Parchuri",
    "Soumya Sri Gudivada",
    "Hima Madhuri Undi",
    "DurgaPrasad Musini",
    "Sri Lakshmi Dasari",
    "Keerthi Priya Chodavarpu",
    "Gorre Manikanta Reddy",
    "Arun Gattadi",
    "Anil Kumar Boya",
    "Pandurang Dawargave",
    "Ambati Rajendra",
    "Jnana Deepika Mukku",
    "Akhila Patibandla",
    "Lalam Padmavati",
    "P S K D Ayyappa Swamy",
    "Harshitha G",
    "Venkata Raviteja Arvapalli",
    "Pranay Nandkishor Burande",
    "Vamsi Raj Chebrolu",
    "Ramya Sri Marella",
    "Soujanya Chinta",
    "Ramya Yarlagadda",
    "Ranjith Kumar Manne",
    "Venkata Sai Ram Bhogadi",
    "Gulam Azad Shaik",
    "Sai Krishna Pitta",
    "Praveen Kumar Talari",
    "Samson Kaleti",
    "Marella Hema Satya Narayana",
    "Venkata Ramana Basetti",
    "Venkata Bhanu Sai Zagabathuni",
    "Alamuri Yamini",
    "Srinivas Sir",
  ];
  
 export  const badmintonPlayers = [
    "Gopi Puppala",
    "Bala Sambasiva Rao N",
    "Roja",
    "Rama Rao B",
    "Vamshi Krishna Nune",
    "Sai Manaswi Ponna",
    "Manjusha Bandaru",
    "Kethan Sri Venkata Sai Annam",
    "N V S Parvathi Annam",
    "Lakshmi Sowmya Parchuri",
    "Soumya Sri Gudivada",
    "Hima Madhuri Undi",
    "DurgaPrasad Musini",
    "Sri Lakshmi Dasari",
    "Keerthi Priya Chodavarpu",
    "Gorre Manikanta Reddy",
    "P S K D Ayyappa Swamy",
    "Harshitha G",
    "Venkata Raviteja Arvapalli",
    "Pranay Nandkishor Burande",
    "Vamsi Raj Chebrolu",
    "Ramya Sri Marella",
    "Soujanya Chinta",
    "Ramya Yarlagadda",
    "Ranjith Kumar Manne",
    "Venkata Sai Ram Bhogadi",
    "Gulam Azad Shaik",
    "Sai Krishna Pitta",
    "Praveen Kumar Talari",
    "Samson Kaleti",
    "Marella Hema Satya Narayana",
    "Venkata Ramana Basetti",
    "Venkata Bhanu Sai Zagabathuni",
    "Alamuri Yamini",
    "Bhanu",
    "Sadhik",
    
  ];

  export const SpAllrounder = [
"Srinivas Sir",
"Bala sambasiva rao n",
"Bhanu kiran",
"Vamsee krishna nune",
"Samson kaleti",
"Durga prasad",]

export const CommonPlayers =[
"Azad shaik",
"Ranjith kumar manne",
"Pitta sai krishna",
"Sai ram bhogadi",
"sai karthik thotakura",
"Hema satya narayana marella",
"Gopi puppala",
"Indra shekar reddy",
]
export const FemalePlayers = [
  "Yaamini",
  "Keerthi priya chodavarpu",
  "Sowmya sri gudivada",
  "sowmya sri parchuri",
  "Hima madhuri undi",
  "Ramya sri marella",
  "Ramya yarlagadda",
  "Manswi ponna",]


  export const ExtraPlayers = [
    "Vamsi raj chebrolu",
    "ketan sri venkata sai annam",
    "venkata ramana basetti",
    "Mani Kanta Reddy",
    "Bhanu sai",
    "Sateesh kumar mogalipuvvu",]